### ISSUE TITLE
Monochrome icon without blue circle

### ISSUE THREAD

**Issue by julienschmidt** [mar-kolya/secure-password-generator#15]
The icon of this extension is the only non-builtin icon I didn't hide behind the "overflow button" in FF57.
However, the icon is driving me slightly crazy because of this blue circle with the checkmark, since it looks a lot like a notification bubble, i.e. asking for the user attention.

Moreover the icon is the only non-monochrome icon and uses a lighter gray than the built-in icon.
![image](https://user-images.githubusercontent.com/944947/32970191-3e0e6920-cbe8-11e7-98a2-19cf70af478e.png)

It would be nice if there was an option for a monochrome logo, preferably in the same gray as built-in icons.

**Comment by mar-kolya** [comment]
I do appreciate your concern, but unfortunately I'm not a graphic designer and it is hard for me to get an appropriate icon. If someone would volunteer an icon under reasonable licence I will happily include it.

**Comment by julienschmidt** [comment]
How about just modifying `resource:///chrome/browser/skin/classic/browser/connection-secure.svg` a bit? That's the icon used to display the TLS status: 
![image](https://user-images.githubusercontent.com/944947/32971786-296fc804-cbef-11e7-9cdb-087c3c54ee80.png)

One could for example just add a keyhole:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/944947/32971776-1ccd68e0-cbef-11e7-9136-248fb9a2d5d3.png">
Nothing special, but it would serve its purpose.

If one includes it as a SVG with the icon in black, it would also be sufficient to make it display in the same color as all the other icons, as Firefox applies the same CSS to webextension buttons.

**Comment by mar-kolya** [comment]
Unfortunately 'CSS' part doesn't seem to be working either. I've tried taking `connection-secure.svg` and using it as an icon. It does get displayed but it stays black regardless of the scheme used - even when other icons change their color. I guess I should file a bug in FF about that.

**Comment by julienschmidt** [comment]
I think there is somehow a difference how those icons are displayed.
For WebExtensions a `<xul:image>` is used and the image is set via `list-style-image: var(--webextension-toolbar-image, inherit);` (where `--webextension-toolbar-image` is a variable containing the image path) while built-in icons use a `<box>` with an background image.
But the [Multi-Account Containers Extension](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) somehow manages to make it work. So it seems like it is still possible.

**Comment by julienschmidt** [comment]
If I replace the SVG URL used by Multi-Account Containers (`"moz-extension://015d019b-51d4-2947-acf2-1908d02c4a38/img/container-site.svg"`) with `"chrome://browser/skin/connection-secure.svg"` or `"resource:///chrome/browser/skin/classic/browser/connection-secure.svg"` it also stops working.

**Comment by mar-kolya** [comment]
I think another problem there would be the fact that chrome doesn't support SVG icons at all. Currently this add-on works in chrome.

**Comment by mar-kolya** [comment]
I've uploaded black icon, close to what you've suggested. I guess this can be closed for now. If/when FF and Chrome start supporting svg I'll upload svg icon.

Thanks for your suggestion!

**Comment by julienschmidt** [comment]
Thanks a  lot!

I'd suggest to also include a light grey version for the dark theme.
And both FF and Chrome use a dark grey tone for their icons, so using something in between FF's and Chrome's grey for the regular icon would probably be the best solution for now.
