### ISSUE TITLE
Conversion of extension to Palemoon browser

### ISSUE THREAD

**Issue by yereverluvinunclebert** [mar-kolya/secure-password-generator#17]
Please use some of your skills to adapt the latest version this extension to PaleMoon. PM is actively supported and your extension in its previous incarnation on FF was one of the most useful. Please revert to an older version to give us the useful pop-up and build a PM compatible version ASAP. There is life in the old dog yet!

I loved this extension on FF as it made password generation so much easier. The previous versions of this extension were superior in that they created a useful pop up which the later versions did not. I do not know why the previous behaviour was abandoned but it was NOT an improvement.

I have 0.51 installed on PaleMoon and it works beautifully just as it should. 

Note:  I have now moved from Firefox to Palemoon as it has an interface that is usable by me after the abortion that is Firefox Australis and Quantum. I have abandoned firefox for Palemoon which is Firefox without all the user interface rubbish that the Mozilla team introduced to make their browser look more like Chrome. It runs faster and is more stable too.

**Comment by mar-kolya** [comment]
I'm glad that you find this addon useful!

Unfortunately the UI change that replaced pop up with drop down is a requirement for newer versions of Firefox. There is no 'pop up window' support in WebExtentions. I would like to support latest FF and Chrome.
For older versions of FF and Palemoon there are always older versions of add-on which should still be available on Mozilla website, or they can be built from this repo.

If you are willing to submit patches to improve PaleMoon support I'll be happy to accept them, but as user of latest FF I will not be able to develop them myself.
