### ISSUE TITLE
Automatically generate password and copy to clipboard

### ISSUE THREAD

**Issue by s-a-m** [mar-kolya/secure-password-generator#19]
Typically, when using the generator, one must:
- Click on the toolbar button to open dialog
- Click on button Generate password
- Click on button Copy to clipboard

I wonder if this could be accelerated suppressing intermediate steps, e.g. 
- Click on the toolbar button to open dialog
- Automatically generates password and copies it to clipboard -> No action required 

Thus, unless one needs to change the default generation options, its use would be much faster, and its usability improved.

**Comment by mar-kolya** [comment]
Hmm. Have you seen context menu that pops up whenever you right click on the password field? It allows you to generate password and insert previously generated password thus providing workflow that is close to what you are describing (with exception of use of clipboard).
