### ISSUE TITLE
Multiprocess support?

### ISSUE THREAD

**Issue by ivoanjo** [mar-kolya/secure-password-generator#2]
Hello!

Thanks for your this kick-ass addon :)

I would like to request that support for multiprocess firefox is added.

**Comment by mar-kolya** [comment]
Hi.

Unfortunately this would mean pretty much rewriting add-on. I'm hoping to be able to do this before FF completely drops XUL, but this is not a trivial change.

**Comment by mar-kolya** [comment]
Should be addressed by b697675

**Comment by ivoanjo** [comment]
Also, looking forward to its release on a.m.o :)
