### ISSUE TITLE
Feature Request: Allow range for password length

### ISSUE THREAD

**Issue by bannisdale** [mar-kolya/secure-password-generator#28]
I use the add-on to generate pretty long passwords to get the highest possible security. However, using the same character count everytime doesn't really seem to support this purpose. Therefore, I randomly change the character count manually every time (e.g. 100, 93, 94, 89, 105 characters). It would be great to have the option of entering a range for the password length (e.g. from 90 to 110).

Thanks for an otherwise really useful and functional add-on!

**Comment by mar-kolya** [comment]
To be honest I do not think there is much usefulness in that: password with any length of 0 < x <= n would have smaller number of variations than password of length n+1. So if you find yourself tuning password length a lot maybe it's time to just increase it by 1 character and be done with it :)

**Comment by wchresta** [comment]
I absolutely agree. Varying password length does not increase security and should thus not be supported since that would imply a false sense of usefulnes.

**Comment by bannisdale** [comment]
Hm. On second thought, your arguments sound reasonable. I was thinking that using the same number of characters (n) everywhere might make it easier to guess (since, as an attacker, you don't have to try n-- and n++) but just increasing it from time to time might actually be the smarter move.

I'm closing this. Thanks for taking the time!
