### ISSUE TITLE
Usage in Firefox for Android is not obvious

### ISSUE THREAD

**Issue by brachiel** [mar-kolya/secure-password-generator#3]
I cannot figure out how to use the generator on the mobile version of Firefox. I can install the addon fine, but there is no UI element to interact with it.

**Comment by mar-kolya** [comment]
Hi @brachiel, thank you for your bugreport.

Unfortunately Firefox for Android doesn't support features necessary for this plugin to work. At this time the only thing I can do is to disable FF for Android compatibility on Mozilla site.

Sorry about that!
