### ISSUE TITLE
Could not be verified for use in Firefox Developer Edition

### ISSUE THREAD

**Issue by betagoo** [mar-kolya/secure-password-generator#30]
Secure Password Generator could not be verified for use in Firefox Developer Edition and has been disabled.
Firefox Developer Edition 67.0b16 (64-bit)

**Comment by mar-kolya** [comment]
Hi. Thanks for the bug report!

I've gotten the same thing in nightly recently - but it disabled all extensions that I use including adblocker and profilier. To me it seems that this is something going on on mozilla side and I'll wait before digging into that.

In fact today I had to rollback my profile directory from backup for unrelated reasons and problem seems to be no longer present.

**Comment by mar-kolya** [comment]
Looks like this is caused by Mozilla certificate expiration.

https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

Dot think is there is anything to be done on add-on side.
