### ISSUE TITLE
be keyboard shortcut friendly

### ISSUE THREAD

**Issue by cmcaine** [mar-kolya/secure-password-generator#6]
It would save me a few clicks to have the password generator copy the password to the clipboard on generation.

Keyboard shortcuts (presumably with browser.commands) for generation and insertion of last would also be useful.

Thanks!

**Comment by mar-kolya** [comment]
Copying to clipboard by default might raise some security questions... But I can see if adding a menu item would be possible.

Would you happen to have suggestions on what those keyboard shortcuts should be?

**Comment by cmcaine** [comment]
If an application can access the keyboard, they can probably access Firefox's memory or the keyboard. Hiding it behind an option is fine, though.

I use vim, so I like un-chorded mnemonic keybinds, but browser.commands requires a chord... Perhaps `alt+g` and `alt+l` for `g`enerate password and insert `l`ast password.

**Comment by mar-kolya** [comment]
I was more thinking about accidentally pasting password somewhere without realizing it has been copied.

**Comment by cmcaine** [comment]
You can get the content of the clipboard in JS using the execCommand API, so passwords in the clipboard are potentially leaked to every web page you visit. Which is a bit of a bummer.

Maybe just the hotkeys. (Could wipe the clipboard after a paste, but it's still riskier).

**Comment by mar-kolya** [comment]
Alt-g and Alt-l should work once 1.0.4 reaches AMO

**Comment by cmcaine** [comment]
Ta
